version: '3'

networks:
    back:
services:
  # FRONTEND
  angular-front:
    build: ./UI/
    ports:
      - "80:80"
    networks:
      - back

  # DB with volume to store data
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    networks:
      - back
    volumes:
      - db-mysql:/var/lib/mysql

  # BACKEND
  node-api:
    depends_on:
        - mysqldb
    build: ./API/
    ports:
      - $NODE_LOCAL_PORT:$NODE_LOCAL_PORT
    networks:
      - back

volumes:
    db-mysql: